spring:
  application:
    name: goldencity-api

    # @EnableJpaAuditing 중복돼서 똑같은 이름의 빈이 두개라도 넘어가도록
    main:
      allow-bean-definition-overriding: true

  profiles:
    active: vault

    data:
      redis:
        # 센티넬 설정
        sentinel:
          master: mymaster          # 레디스 센티넬에서 설정한 마스터 이름
          nodes: # 센티넬 노드 리스트 (보통 3대)
            - 127.0.0.1:26379
            - 127.0.0.1:26380
            - 127.0.0.1:26381
        # 센티넬을 사용하더라도 비밀번호가 있다면 추가 (없으면 생략)
        # password: ${REDIS_PASSWORD:}
        lettuce:
          pool:
            max-active: 10
            max-idle: 10
            min-idle: 2

          cache:
            type: redis
            redis:
              time-to-live: 600000 # 10분

  # 데이터베이스 설정
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/goldencity?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:1234}
    driver-class-name: com.mysql.cj.jdbc.Driver
#    hikari:
#      maximum-pool-size: 20
#      minimum-idle: 10
#      connection-timeout: 30000
#      idle-timeout: 600000
#      max-lifetime: 1800000

  # JPA 설정
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
        default_batch_fetch_size: 100
    open-in-view: false

# Virtual Thread 설정
spring.threads.virtual.enabled: true

# 서버 설정
server:
  port: 8080
  tomcat:
    threads:
      max: 200
      min-spare: 10

# 외부 API 설정 (날씨 API용)
api:
  weather:
    # ${WEATHER_API_KEY} > 공공데이터포털에서 가지고온거라 경주랑 서비스키 같아서 그냥 경주키 쓰는걸로 바꿈
    service-key: ${GYEONGJU_API_KEY}
#    service-key: DYntKt54SX4+YIIoHhNOSec4TrzQMi3ucupYBBtFYcKm3PG9pVVx/YkDiMe6y3p0WUNyhKSfzAKlB6mrnFgv3g==
    url: http://apis.data.go.kr/1360000/VilageFcstInfoService_2.0/getVilageFcst
    nx: 102  # 경주시청 격자 X
    ny: 84   # 경주시청 격자 Y
    timeout:
      connect: 10000
      read: 30000

# 로깅
logging:
  level:
    com.goldencity.api: INFO
    org.springframework.web: INFO
    org.springframework.cache: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"